apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  volumes:
  - name: ashuv1
    emptyDir: {}
  - name: ashuv2 
    nfs: 
      server: ip
      path: /data/log/
  containers:
  - image: httpd:logv1
    name: pod1
    volumeMounts:
    - name: ashuv1 
      mountPath: /var/log/httpd/access/
    - name: ashuv2
      mountPath: /var/log/httpd/error/
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
