apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ashu-disk2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi 
  resources:
    requests:
      storage: 20Gi

---
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: nginx
      volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume1
          readOnly: false
  volumes:
    - name: volume1
      persistentVolumeClaim:
        claimName: ashu-disk2

---