apiVersion: v1
kind: ReplicationController 
metadata:
  labels:
    new: ashurc4545
  name: ashurc2     
spec: 
  replicas: 1
  selector: # for finding 
    x: helloashu
    z: dev 
  template: # RC will be using Template to create Pods 
    metadata:
      labels: # this is label of pods during creation 
        x: helloashu  
        z: dev  
    spec: 
      containers:
      - image: nginx 
        name: ashuc1 