apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashu-dep1
  name: ashu-lb # name of Internal LB 
spec:
  ports:
  - port: 80 # LB port 
    protocol: TCP
    targetPort: 80 # pod port 
  selector: # pod finder using label of pod 
    app: ashu-dep1
  type: LoadBalancer # type of service 
status:
  loadBalancer: {}
