apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-dep1
  name: ashu-dep1 # name of deployment 
spec:
  replicas: 1 # pod required 
  selector:
    matchLabels:
      app: ashu-dep1
  strategy: {} # upgrading strategy rolling updates by default 
  template: # use to create pod 
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-dep1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
