apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashu-dep1
  name: ashulb1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ashu-dep1
  type: LoadBalancer
status:
  loadBalancer: {}
