apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jpmc-cluster
  region: ap-south-1
  version: "1.29"

nodeGroups:
  - name: nodepool-1
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 200
    ssh:
      allow: true 
      publicKeyPath: /Users/humanfirmware/.ssh/id_rsa.pub


fargateProfiles:
  - name: ashu-profile1
    selectors:
      - namespace: default
