apiVersion: v1
kind: PersistentVolume
metadata:
  name: ashu-pv-2
  labels:
    type: local1
spec:
  storageClassName: manual 
  capacity:
    storage: 2Gi  # 1GB == 1000MB -- 1GiB == 1024 MiB
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-2"
    type: DirectoryOrCreate
